[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sendsol2024 = "5ZPzPodxYJ4ce4n395fR9MsX6HnmY9Cez3181mw5FNY6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/beliv/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
